cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    fagzz:
      email: fagzz
      name: fagzz
      password: $2b$12$Fi.PLplVp.MPqBuvDqBPlutKaf2D7Z6PU9Dc3ajks4V6M8tkAYsai
    grimzz:
      email: grimzz
      name: grimzz
      password: grimzz
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: $2b$12$qn8BCmHDK1wB/YU9sZ3cWOG8uRQaBW44PVEBU.2mxTIrndKlVwxO.
    pfaguz:
      email: pfaguz
      name: pfaguz
      password: $2b$12$oJ1nUFmy5M7r0.mpIy.zaONMIFQMlB7jFb8cy/lqsGl/QT1bPMjf2
    pfagz:
      email: pfagz@gmail.com
      name: pfagz
      password: $2b$12$yi7VwMdzsxXuDu2J7emL1ujFpvkDKCtjJjRmQbD8SXBfc4FrwibSO
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: $2b$12$so.A1ZCofCALAon.kmxm1eryRCTtIFHy0bViSxhqsENuxnKrAUxgO
preauthorized:
  emails:
  - melsby@gmail.com
  - pfagz
  - pfaguz
  - fagzz
  - grimzz
