cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    faguzer:
      email: faguzer
      name: faguzer
      password: $2b$12$UkA8XRHp2o.uAbDjG9CR.O6b2/m0nb.TZRiAn0AQCuAnt4I9rH1Na
    fagzz:
      email: fagzz
      name: fagzz
      password: $2b$12$Fi.PLplVp.MPqBuvDqBPlutKaf2D7Z6PU9Dc3ajks4V6M8tkAYsai
    pfaguz:
      email: pfaguz
      name: pfaguz
      password: $2b$12$oJ1nUFmy5M7r0.mpIy.zaONMIFQMlB7jFb8cy/lqsGl/QT1bPMjf2
    pfagz:
      email: pfagz@gmail.com
      name: pfagz
      password: $2b$12$yi7VwMdzsxXuDu2J7emL1ujFpvkDKCtjJjRmQbD8SXBfc4FrwibSO
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: $2b$12$so.A1ZCofCALAon.kmxm1eryRCTtIFHy0bViSxhqsENuxnKrAUxgO
    tess:
      email: tess
      name: tess
      password: $2b$12$0wzq/BC2QbaqmPA81/fhUumugGzrUgiVPKh/5MPjrQT1t.Le7xtAW
    tessa:
      email: tessa
      name: tessa
      password: $2b$12$X9QkjYersrNf73.9f61mWuMfvU9SFzAdj6mpmp.MUu2.oNgHL9l1S
    test:
      email: test
      name: test
      password: $2b$12$8AisJ5JzMjtzuoy2fjU4Eey92695d78TYgDrHEFRXQ4vH30edi1HK
    user:
      email: user
      name: user
      password: $2b$12$k43P5bxSuQNpev.sIVhON.ThILGWD3dXNA5baO66JiTKQVFYO/FOK
preauthorized:
  emails:
  - melsby@gmail.com
  - pfagz
  - pfaguz
  - fagzz
  - grimzz
  - faguzer@gmail.com
  - faguzer
  - test
  - test
  - test
  - user
  - test
  - tess
  - tessa
